name: the_menu
description: "Projeto de cardápio digital/delivery para a A3 - Sistemas Distribuídos e Mobile."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  solar_icons: ^0.0.5
  get: ^4.6.6
  dart_mappable: ^4.2.2
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  dart_mappable_builder: ^4.2.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - "assets/"

flutter_launcher_icons:
  image_path: "assets/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_foreground: "assets/adaptive_icon_fg.png"
  adaptive_icon_background: "assets/adaptive_icon_bg.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true
  web: true
